export const allCategories = [
	{category: 'Живопись', thumbnail: './images/dist/gallery1.jpg'},
	{category: 'Живопись', thumbnail: './images/dist/gallery2.jpg'},
	{category: 'Живопись', thumbnail: './images/dist/gallery3.jpg'},
	{category: 'Рисунок', thumbnail: './images/dist/gallery4.jpg'},
	{category: 'Живопись', thumbnail: './images/dist/gallery5.jpg'},
	{category: 'Рисунок', thumbnail: './images/dist/gallery6.jpg'},
	{category: 'Живопись', thumbnail: './images/dist/gallery7.jpg'},
	{category: 'Живопись', thumbnail: './images/dist/gallery8.jpg'},
	{category: 'Рисунок', thumbnail: './images/dist/gallery9.jpg'},
	{category: 'Живопись', thumbnail: './images/dist/gallery10.jpg'},
	{category: 'Рисунок', thumbnail: './images/dist/gallery11.jpg'},
	{category: 'Живопись', thumbnail: './images/dist/gallery12.jpg'},
	{category: 'Рисунок', thumbnail: './images/dist/gallery13.jpg'},
	{category: 'Рисунок', thumbnail: './images/dist/gallery14.jpg'},
	{category: 'Рисунок', thumbnail: './images/dist/gallery15.jpg'},
	{category: 'Рисунок', thumbnail: './images/dist/gallery16.jpg'},
	{category: 'Скульптура', thumbnail: './images/dist/gallery17.jpg'},
	{category: 'Скульптура', thumbnail: './images/dist/gallery18.jpg'},
	{category: 'Скульптура', thumbnail: './images/dist/gallery19.jpg'},
	{category: 'Скульптура', thumbnail: './images/dist/gallery20.jpg'},
	{category: 'Скульптура', thumbnail: './images/dist/gallery21.jpg'},
	{category: 'Скульптура', thumbnail: './images/dist/gallery22.jpg'},
	{category: 'Скульптура', thumbnail: './images/dist/gallery23.jpg'},
	{category: 'Скульптура', thumbnail: './images/dist/gallery24.jpg'},
]